### ISSUE TITLE
Fix failing unit tests (v0.16)

### ISSUE THREAD

**Issue by MagnusS** [includeos/IncludeOS#2253]
The following tests are currently failing on v0.16 branch (from #2250):

- [x] 2 - path_test (SEGFAULT) #2255
- [x] 12 - memmap_test (Failed) #2254
- [x] 14 - os_test (Failed) #2256 
- [x] 21 - x86_paging (SEGFAULT) #2255 
- [x] 25 - cidr (SEGFAULT) #2255 
- [x] 28 - dhcp (SEGFAULT) #2256
- [x] 50 - router_test (Failed) #2256
- [x] 54 - tcp_packet_test (SEGFAULT) #2255
- [x] 67 - fixed_list_alloc_test (SEGFAULT) #2262
- [x] 71 - logger_test (Failed) #2259
- [x] 82 - test_lstack_nodes (SEGFAULT) #2255 
- [x] 83 - test_lstack_merging (SEGFAULT) #2255 
- [x] 84 - test_lstack_nomerge (SEGFAULT) #2255 

To run the unit tests, see details in #2250 -- or just run `nix-build unittests.nix`

**Comment by MagnusS** [comment]
The `x86_paging` failure is caused by the `EXPECT_THROWS` in https://github.com/includeos/IncludeOS/blob/v0.16.0-release/test/kernel/unit/x86_paging.cpp#L217. 

When `__expect_fails` in https://github.com/includeos/IncludeOS/blob/v0.16.0-release/api/expects#L35 is called it proceeds to call `os::panic`, which results in a segfault. `EXPECT_THROWS` doesn't capture the expected failure and the test fails.

Several of the other tests also fail with segfaults, so fixing this could potentially fix all of them (unless we have more failures of course...).

**Comment by MagnusS** [comment]
Only 2 more tests to go.

I had a quick look at `fixed_list_alloc_test` and it seems to segfault here: https://github.com/includeos/IncludeOS/blob/v0.16.0-release/test/util/unit/fixed_list_alloc_test.cpp#L38

**Comment by MagnusS** [comment]
The tests are now working so closing this issue -- links to PRs are in the updated issue description
