### ISSUE TITLE
v0.16 tracking issue

### ISSUE THREAD

**Issue by MagnusS** [includeos/IncludeOS#2286]
Move v0.16.0 to master and tag a new release.

Checklist:
- [ ] Update README with new nix build instructions
- [ ] Add CHANGELOG with recent PRs
- [ ] Update README in hello_world (open PR https://github.com/includeos/hello_world/pull/12) 
- [ ] Archive unused repos
    - [ ] https://github.com/includeos/includeos-tools (no longer needed?)
    - [ ] https://github.com/includeos/homebrew-includeos (no longer needed)
    - [ ] https://github.com/includeos/conan_config (replaced)
    - [ ] https://github.com/includeos/conan (replaced)
    - [ ] https://github.com/includeos/musl (now downloaded by nix)
    - [ ] https://github.com/includeos/vmbuild (moved to includeos repo)
    - [ ] others?
 - [ ] Make v0.16.0-release branch new master
 - [ ] Tag and write release notes
